### ISSUE TITLE
Feature Request: Alarm Code sensor

### ISSUE THREAD

**Issue by waako** [alepee/hass-hitachi_yutaki#1]
On my setup I pull in the alarm code (registry address 1223) so I can at least do a lookup.

Would it be possible to include this, and how viable would it be to have a mapping of alarm code to the information from manuals:
- Origin of alarm (indoor, outdoor)
- Details
- Cause 

I have extracted/compiled all the alarm codes and their meaning from the manuals into a google sheet for reference, happy to help develop it if I can 😄 
https://docs.google.com/spreadsheets/d/1wre213jwXUcMTb9USZfI3wNzx-fjKmIm5UlkeyY76gM/edit?usp=sharing

Maybe sensor state could be: "Detail of alarm (code)" for example: "Low water pressure (83)" but use attributes for extra info:
- `alarm_code`
- `origin`
- `cause`

**Comment by alepee** [comment]
Super idée 👍 
Où as-tu récupéré la liste des codes erreurs ? Est-ce que tu saurais trouver les codes pour les Yukati M et S80 ?

**Comment by waako** [comment]
J'ai mis le nom des documents sur l'onglet ["Info & Legend"](https://docs.google.com/spreadsheets/d/1wre213jwXUcMTb9USZfI3wNzx-fjKmIm5UlkeyY76gM/edit)

Mais on doit pouvoir trouver les manuels pour les autres sur https://documentation.hitachiaircon.com/fr/fr/chauffage (cependant y'as rien dans les pages pour S80 🙁)

**Comment by waako** [comment]
Je viens de mettre à jour les onglets `EN: Indoor units` et `EN: LCD Display` avec colonnes pour indiquer si le code erreur est valide pour:

- Yutaki S80
- Yutaki M 
- PC-ARFH1E
- PC-ARFH2E 

De plus, j'ai dupliqué le code erreurs avec des info différentes selon controleur PC-ARFH1E ou PC-ARFH2E

Reste à faire pareil avec les onglets FR

**Comment by alepee** [comment]
https://github.com/alepee/hass-hitachi_yutaki/releases/tag/1.1.1
